### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by DenisCarriere** [dongli/legacy-starman#4]
Hey @dongli this looks like you put a lot of effort into this project, however could you provide more documentation on how to use it? Improving the docs might increase new contributors to your project and it would help "newbies" like myself to know what this tool does.

Best of luck and I'm looking forward to try out `STARMAN`.

You can close this issue once you've read it.

**Comment by dongli** [comment]
Hi, @DenisCarriere Thanks for your warm greeting and good suggestion! I started to write `starman` to solve my own problems about setup dev environment several years ago, and I have gained a lot of skills during this course, such as build many kinds of softwares : ). It works like `homebrew` but with consideration on other Linux OSs. But, it's a pity that `starman` didn't draw a lot of attentions like `homebrew`. Documentation is always my pain because I have strict time scheduler or maybe just lazy : P. Currently, I am using Docker a lot, and found it is a worry-saver, so my development on `starman` may slow down. If you are still interested, I can listed the functions and places to be improved of `starman`. Cheers!

**Comment by DenisCarriere** [comment]
I'm a Docker fan as well, if you are saying that `homebrew` & `Docker` does similar things, then I would stick with those and keep this project as a "nice to learn things".

👍 Keep it up on your next projects! I'm sure you'll do great things! 🚀

**Comment by dongli** [comment]
`homebrew` and `Docker` all provide a unique environment, but `homebrew` is limited to macOS (there is a `linuxbrew`, but I haven't check it out for a long time). So I am switching to `Docker` right now, but the time I spent on `starman` will not be in vain, you can found some useful tips about building software there (I hope so~).

**Comment by DenisCarriere** [comment]
👍 Nice stuff! I'm a fan of Docker
